# Generated by Django 5.0 on 2024-01-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image_url",
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="Project_images/"),
        ),
    ]
