# Generated by Django 5.0 on 2024-01-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_remove_project_image_url_project_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="team_images/"),
                ),
            ],
        ),
    ]
